
class ShaderType:
    POINTS      = "POINTS"
    LINES       = "LINES"
    TRIS        = "TRIS"
    LINE_STRIP  = "LINE_STRIP"
    LINE_LOOP   = "LINE_LOOP" # DEPRECATED
    LINES_ADJ   = "LINES_ADJ" # DEPRECATED
    TRI_FAN     = "TRIS" # DEPRECATED
    TRIS_ADJ    = "TRIS_ADJ"
    LINE_STRIP_ADJ  = "LINE_STRIP_ADJ" # DEPRECATED
    TRI_STRIP   = "TRI_STRIP"
    IMG         = TRIS # DEPRECATED
