# /icons.py
# Code automatically generated!
from pathlib import Path
from bl_ext.user_default.sculpt_plus.ackit._auto_code_gen.icons import IconsEnum, IconsViewer

icons_dirpath = Path("lib/icons")


class Icons(IconsViewer):

	class FACE_SETS(IconsEnum):
		BOX_FACESET_ICON = icons_dirpath / "face_sets/Box_FaceSet_icon.png"
		DRAW_FACESETS_ICON_OLD = icons_dirpath / "face_sets/Draw_FaceSets_icon_old.png"
		FACESETGROW_ICON = icons_dirpath / "face_sets/FaceSetGrow_icon.png"
		FACESETGROW_ICON2 = icons_dirpath / "face_sets/FaceSetGrow_icon2.png"
		FACESETSHRINK_ICON = icons_dirpath / "face_sets/FaceSetShrink_icon.png"
		FACESETSHRINK_ICON2 = icons_dirpath / "face_sets/FaceSetShrink_icon2.png"
		FACESETSSCALEDOWN_ICON = icons_dirpath / "face_sets/FaceSetsScaleDown_icon.png"
		FACESETSSCALEUP_ICON = icons_dirpath / "face_sets/FaceSetsScaleUp_icon.png"
		FACESETS_ICON = icons_dirpath / "face_sets/FaceSets_icon.png"
		FRONTFACES_ICON = icons_dirpath / "face_sets/frontFaces_icon.png"
		LASSO_FACESET_ICON = icons_dirpath / "face_sets/Lasso_FaceSet_icon.png"

	class MASK(IconsEnum):
		BOX_MASK_ICON = icons_dirpath / "mask/Box_Mask_icon.png"
		LASSO_MASK_ICON = icons_dirpath / "mask/Lasso_Mask_icon.png"
		MASKCAVITY_ICON = icons_dirpath / "mask/MaskCavity_icon.png"
		MASKCLEAR_ICON = icons_dirpath / "mask/MaskClear_icon.png"
		MASKCONTRASTDOWN_ICON_FLAT = icons_dirpath / "mask/MaskContrastDown_icon_flat.png"
		MASKCONTRASTUP_ICON_FLAT = icons_dirpath / "mask/MaskContrastUp_icon_flat.png"
		MASKEXTRACTOR_ICON = icons_dirpath / "mask/maskExtractor_icon.png"
		MASKEXTRACT_ICON = icons_dirpath / "mask/MaskExtract_icon.png"
		MASKEXTRACT_ICON2 = icons_dirpath / "mask/MaskExtract_icon2.png"
		MASKGROW_ICON = icons_dirpath / "mask/MaskGrow_icon.png"
		MASKGROW_ICON2 = icons_dirpath / "mask/MaskGrow_icon2.png"
		MASKINVERT_ICON = icons_dirpath / "mask/MaskInvert_icon.png"
		MASKRANDOM_ICON = icons_dirpath / "mask/MaskRandom_icon.png"
		MASKSCALEDOWN_ICON = icons_dirpath / "mask/MaskScaleDown_icon.png"
		MASKSCALEDOWN_ICON3 = icons_dirpath / "mask/MaskScaleDown_icon3.png"
		MASKSCALEDOWN_ICON_FLAT = icons_dirpath / "mask/MaskScaleDown_icon_flat.png"
		MASKSCALEUP_ICON = icons_dirpath / "mask/MaskScaleUp_icon.png"
		MASKSCALEUP_ICON2 = icons_dirpath / "mask/MaskScaleUp_icon2.png"
		MASKSCALEUP_ICON3 = icons_dirpath / "mask/MaskScaleUp_icon3.png"
		MASKSCALEUP_ICON4 = icons_dirpath / "mask/MaskScaleUp_icon4.png"
		MASKSCALEUP_ICON_FLAT = icons_dirpath / "mask/MaskScaleUp_icon_flat.png"
		MASKSHARP_ICON = icons_dirpath / "mask/MaskSharp_icon.png"
		MASKSHRINK_ICON = icons_dirpath / "mask/MaskShrink_icon.png"
		MASKSHRINK_ICON2 = icons_dirpath / "mask/MaskShrink_icon2.png"
		MASKSLICE_ICON = icons_dirpath / "mask/MaskSlice_icon.png"
		MASKSMOOTH1_ICON = icons_dirpath / "mask/MaskSmooth1_icon.png"
		MASKSMOOTH2_ICON = icons_dirpath / "mask/MaskSmooth2_icon.png"
		MASKSMOOTH_ICON = icons_dirpath / "mask/MaskSmooth_icon.png"
		MASK_ICON = icons_dirpath / "mask/Mask_icon.png"

	class MAIN(IconsEnum):
		ADD_67 = icons_dirpath / "add-67.png"
		ADD_ROW_50 = icons_dirpath / "add-row-50.png"
		ADD_TO_INBOX_24 = icons_dirpath / "add-to-inbox-24.png"
		ADD_WEBPAGE_48 = icons_dirpath / "add-webpage-48.png"
		ADD_2_67 = icons_dirpath / "add_2-67.png"
		ARROWDOWN_ICON = icons_dirpath / "ArrowDown_icon.png"
		ARROWUP_ICON = icons_dirpath / "ArrowUp_icon.png"
		BAR_32 = icons_dirpath / "bar-32.png"
		BLENDER_ICON_64X64 = icons_dirpath / "blender_icon_64x64.png"
		BOOK_SHELF_96 = icons_dirpath / "book-shelf-96.png"
		BOOKS_96 = icons_dirpath / "books-96.png"
		BROOM_64 = icons_dirpath / "broom-64.png"
		BRUSHADD_ICON = icons_dirpath / "brushAdd_icon.png"
		BRUSHES_1_64 = icons_dirpath / "brushes_1_64.png"
		BRUSHES_2_64 = icons_dirpath / "brushes_2_64.png"
		BRUSHLIB_64 = icons_dirpath / "brushlib_64.png"
		BRUSHREMOVE_ICON = icons_dirpath / "brushRemove_icon.png"
		BRUSHRESET_ICON = icons_dirpath / "brushReset_icon.png"
		BRUSH_ICON = icons_dirpath / "brush_icon.png"
		CALENDAR_PLUS_30 = icons_dirpath / "calendar-plus-30.png"
		CHANGE_24 = icons_dirpath / "change-24.png"
		CHANGE_48 = icons_dirpath / "change-48.png"
		CHANGE_50 = icons_dirpath / "change-50.png"
		CLOSE_48 = icons_dirpath / "close-48.png"
		DIAGONAL_LINES_60 = icons_dirpath / "diagonal-lines-60.png"
		DOWNLOAD_52 = icons_dirpath / "download-52.png"
		DRAWING_100 = icons_dirpath / "drawing-100.png"
		EXPAND_ICON = icons_dirpath / "Expand_icon.png"
		FALLOFF_ICON = icons_dirpath / "fallOff_icon.png"
		FILL_DRIP_32 = icons_dirpath / "fill-drip-32.png"
		IMAGE_64 = icons_dirpath / "image-64.png"
		IMPORT_48 = icons_dirpath / "import-48.png"
		MINUS_64 = icons_dirpath / "minus-64.png"
		MIRROR_ICON = icons_dirpath / "Mirror_icon.png"
		MOVE_DOWN_ROW_30 = icons_dirpath / "move-down-row-30.png"
		MOVE_SELECTION_TO_TOP_ROW_40 = icons_dirpath / "move-selection-to-top-row-40.png"
		MOVE_SELECTION_TO_TOP_ROW_40_NO_BG = icons_dirpath / "move-selection-to-top-row-40_no_bg.png"
		MOVE_UP_ROW_30 = icons_dirpath / "move-up-row-30.png"
		PAINT_BRUSH_50 = icons_dirpath / "paint-brush-50.png"
		PAINTBRUSH_64 = icons_dirpath / "paintbrush-64.png"
		PENCIL_CASE_64 = icons_dirpath / "pencil-case-64.png"
		PENCIL_CASE_99 = icons_dirpath / "pencil-case-99.png"
		PSD_1_96 = icons_dirpath / "psd-1-96.png"
		PSD_2_64 = icons_dirpath / "psd-2-64.png"
		REMOVE_30 = icons_dirpath / "remove-30.png"
		RIGHTARROW_ICON = icons_dirpath / "RightArrow_icon.png"
		SCALEDOWN_ICON = icons_dirpath / "ScaleDown_icon.png"
		SCALEUP_ICON = icons_dirpath / "ScaleUp_icon.png"
		SEARCH_ICON = icons_dirpath / "Search_icon.png"
		SHRINK_ICON = icons_dirpath / "Shrink_icon.png"
		STROKEAIRBRUSH_ICON = icons_dirpath / "strokeAirbrush_icon.png"
		STROKEANCHORED_ICON = icons_dirpath / "strokeAnchored_icon.png"
		STROKECURVE_ICON = icons_dirpath / "strokeCurve_icon.png"
		STROKEDOTS_ICON = icons_dirpath / "strokeDots_icon.png"
		STROKEDRAGDOT_ICON = icons_dirpath / "strokeDragDot_icon.png"
		STROKELINE_ICON = icons_dirpath / "strokeLine_icon.png"
		STROKESPACE_ICON = icons_dirpath / "strokeSpace_icon.png"
		STROKE_ICON = icons_dirpath / "stroke_icon.png"
		TEXTURE_48 = icons_dirpath / "texture-48.png"
		TEXTURE_OPACITY_48 = icons_dirpath / "texture-opacity-48.png"
		TEXTURE_SMALL_24 = icons_dirpath / "texture-small-24.png"
		TEXTURENEW_ICON = icons_dirpath / "textureNew_icon.png"
		TEXTUREOPEN_ICON = icons_dirpath / "textureOpen_icon.png"
		TEXTURE_ICON = icons_dirpath / "texture_icon.png"
		TRANSFORMMULTI_ICON = icons_dirpath / "TransformMulti_icon.png"
		TRANSFORMROTATE_ICON = icons_dirpath / "TransformRotate_icon.png"
		TRANSFORMSCALE_ICON = icons_dirpath / "TransformScale_icon.png"
		TRANSFORMTRANSLATE_ICON = icons_dirpath / "TransformTranslate_icon.png"

